name: CICD pipeline 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build the artifact
        run: mvn clean package

  sonarqube:
     runs-on: self-hosted
     needs: build
     steps:
      - name: Sonarbue report
        run: mvn sonar:sonar

  security-check:
    runs-on: self-hosted
    need: sonarqube
    steps:
      - name: install the trivy 
        run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.67.2_Linux-64bit.deb
      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .









